const charginStationKeys = [
  "nom_operateur",
  "telephone_operateur",
  "nom_enseigne",
  "implantation_station",
  "adresse_station",
  "coordonneesXY",
  "nbre_pdc",
  "puissance_nominale",
  "prise_type_ef",
  "prise_type_2",
  "prise_type_combo_ccs",
  "prise_type_chademo",
  "prise_type_autre",
  "tarification",
  "condition_acces",
  "reservation",
  "horaires",
  "accessibilite_pmr",
  "restriction_gabarit",
  "consolidated_longitude",
  "consolidated_latitude",
];

const chargingStationToCreate = {
  nom_operateur: "ELECTRIC 55 CHARGING",
  telephone_operateur: "33975891501",
  nom_enseigne: "ELECTRIC 55 CHARGING",
  implantation_station: "Voirie",
  adresse_station: "1 Avenue Victor Basch 84300 Cavaillon",
  coordonneesXY: [5.042062, 43.836565],
  nbre_pdc: 1,
  puissance_nominale: 22,
  prise_type_ef: "TRUE",
  prise_type_2: "TRUE",
  prise_type_combo_ccs: "FALSE",
  prise_type_chademo: "FALSE",
  prise_type_autre: "FALSE",
  tarification: "",
  condition_acces: "AccÃ¨s rÃ©servÃ©",
  reservation: "TRUE",
  horaires: "24/7",
  accessibilite_pmr: "Accessible mais non rÃ©servÃ© PMR",
  restriction_gabarit: "15mÂ²",
  consolidated_longitude: 5.042062,
  consolidated_latitude: 43.836565,
};

module.exports = {
  charginStationKeys,
  chargingStationToCreate,
};
